{
  "hash": "8df29fae1f447213925308d5864e30cc",
  "result": {
    "markdown": "---\ntitle: \"Randomized Controlled Trials\"\n---\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-1_517c0a72484f31daf3555cc5a52ef698'}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: Paket 'tidyverse' wurde unter R Version 4.3.2 erstellt\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: Paket 'tidyr' wurde unter R Version 4.3.2 erstellt\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: Paket 'readr' wurde unter R Version 4.3.2 erstellt\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: Paket 'purrr' wurde unter R Version 4.3.2 erstellt\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: Paket 'forcats' wurde unter R Version 4.3.2 erstellt\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Warning: Paket 'lubridate' wurde unter R Version 4.3.2 erstellt\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n#> ✔ dplyr     1.1.3     ✔ readr     2.1.4\n#> ✔ forcats   1.0.0     ✔ stringr   1.5.0\n#> ✔ ggplot2   3.4.4     ✔ tibble    3.2.1\n#> ✔ lubridate 1.9.3     ✔ tidyr     1.3.0\n#> ✔ purrr     1.0.2     \n#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n#> ✖ dplyr::filter() masks stats::filter()\n#> ✖ dplyr::lag()    masks stats::lag()\n#> ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\n# Load the data\nabtest_data <- readRDS(\"C:\\\\Users\\\\Deniz\\\\Documents\\\\GitHub\\\\Causal_Data_Science_Data\\\\abtest_online.rds\")\n\n# Explore the data\nhead(abtest_data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"ip\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"chatbot\"],\"name\":[2],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"previous_visit\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mobile_device\"],\"name\":[4],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"purchase\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"purchase_amount\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"161.88.211.70\",\"2\":\"TRUE\",\"3\":\"0\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"239.86.201.0\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"1\",\"6\":\"39.45626\"},{\"1\":\"35.90.22.130\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"219.176.193.3\",\"2\":\"FALSE\",\"3\":\"4\",\"4\":\"TRUE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"247.85.168.16\",\"2\":\"TRUE\",\"3\":\"1\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"},{\"1\":\"120.221.249.244\",\"2\":\"TRUE\",\"3\":\"2\",\"4\":\"FALSE\",\"5\":\"0\",\"6\":\"0.00000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsummary(abtest_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>       ip             chatbot        previous_visit   mobile_device  \n#>  Length:1000        Mode :logical   Min.   : 0.000   Mode :logical  \n#>  Class :character   FALSE:496       1st Qu.: 1.000   FALSE:683      \n#>  Mode  :character   TRUE :504       Median : 1.000   TRUE :317      \n#>                                     Mean   : 2.021                  \n#>                                     3rd Qu.: 3.000                  \n#>                                     Max.   :13.000                  \n#>     purchase     purchase_amount\n#>  Min.   :0.000   Min.   : 0.00  \n#>  1st Qu.:0.000   1st Qu.: 0.00  \n#>  Median :0.000   Median : 0.00  \n#>  Mean   :0.381   Mean   :13.14  \n#>  3rd Qu.:1.000   3rd Qu.:27.44  \n#>  Max.   :1.000   Max.   :81.35\n```\n:::\n\n```{.r .cell-code}\n# Check covariate balance across groups\ncovariate_balance_plot <- ggplot(abtest_data, aes(x = chatbot, y = mobile_device, color = chatbot)) +\n  geom_boxplot() +\n  labs(title = \"Covariate Balance Check\",\n       x = \"Chatbot\",\n       y = \"Mobile Device\") +\n  theme_minimal()\n\n# Display covariate balance plot\nprint(covariate_balance_plot)\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Run a regression to find the effect of chatbot on sales (purchase_amount)\nregression_model <- lm(purchase_amount ~ chatbot + mobile_device + previous_visit, data = abtest_data)\nsummary(regression_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase_amount ~ chatbot + mobile_device + previous_visit, \n#>     data = abtest_data)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -25.414 -14.428  -8.435  12.559  64.584 \n#> \n#> Coefficients:\n#>                   Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)        15.2840     1.1227  13.614  < 2e-16 ***\n#> chatbotTRUE        -6.8488     1.1792  -5.808 8.49e-09 ***\n#> mobile_deviceTRUE  -0.8562     1.2642  -0.677  0.49841    \n#> previous_visit      0.7792     0.2869   2.716  0.00673 ** \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 18.6 on 996 degrees of freedom\n#> Multiple R-squared:  0.04243,\tAdjusted R-squared:  0.03954 \n#> F-statistic: 14.71 on 3 and 996 DF,  p-value: 2.228e-09\n```\n:::\n\n```{.r .cell-code}\n# Find subgroup-specific effects by including an interaction term\ninteraction_model <- lm(purchase_amount ~ chatbot * mobile_device + previous_visit, data = abtest_data)\nsummary(interaction_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase_amount ~ chatbot * mobile_device + previous_visit, \n#>     data = abtest_data)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -25.403 -14.450  -8.445  12.549  64.562 \n#> \n#> Coefficients:\n#>                               Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)                   15.27384    1.19130  12.821  < 2e-16 ***\n#> chatbotTRUE                   -6.82837    1.42580  -4.789 1.93e-06 ***\n#> mobile_deviceTRUE             -0.82375    1.79309  -0.459  0.64605    \n#> previous_visit                 0.77914    0.28711   2.714  0.00677 ** \n#> chatbotTRUE:mobile_deviceTRUE -0.06455    2.52907  -0.026  0.97964    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 18.6 on 995 degrees of freedom\n#> Multiple R-squared:  0.04243,\tAdjusted R-squared:  0.03858 \n#> F-statistic: 11.02 on 4 and 995 DF,  p-value: 9.485e-09\n```\n:::\n\n```{.r .cell-code}\n# Compute CATE for mobile users\nmobile_users_effect <- coef(interaction_model)[\"chatbotTRUE:mobile_deviceTRUE\"]\n\n# Run a logistic regression for binary outcome (purchase)\nlogistic_model <- glm(purchase ~ chatbot + mobile_device + previous_visit, \n                      family = binomial(link = 'logit'), data = abtest_data)\nsummary(logistic_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> glm(formula = purchase ~ chatbot + mobile_device + previous_visit, \n#>     family = binomial(link = \"logit\"), data = abtest_data)\n#> \n#> Coefficients:\n#>                   Estimate Std. Error z value Pr(>|z|)    \n#> (Intercept)       -0.22185    0.12347  -1.797  0.07237 .  \n#> chatbotTRUE       -0.96894    0.13564  -7.144 9.09e-13 ***\n#> mobile_deviceTRUE -0.07119    0.14530  -0.490  0.62417    \n#> previous_visit     0.10606    0.03262   3.252  0.00115 ** \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 1329.1  on 999  degrees of freedom\n#> Residual deviance: 1262.2  on 996  degrees of freedom\n#> AIC: 1270.2\n#> \n#> Number of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\n\n\n2. chatbotTRUE: The estimated change in purchase_amount when chatbot is TRUE compared to when it is FALSE. A negative coefficient suggests that the presence of a chatbot is associated with a decrease in purchase_amount.\n\n\n3. The CATE for mobile users (chatbotTRUE:mobile_deviceTRUE)is -0.06455 in the model. However, this coefficient is not statistically significant, indicating that there is no significant distinction in the impact of the chatbot on sales (purchase_amount) between mobile and non-mobile users.\n\n4. Coefficient for chatbotTRUE in the logistic regression model is -0.96894. Therefore:\n\nA negative coefficient suggests that the presence of the chatbot is associated with a decrease in the log-odds of making a purchase compared to when the chatbot is not present. It implies that customers exposed to the chatbot are less likely to make a purchase (purchase = 1) compared to those not exposed, according to the model.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}