{
  "hash": "0258271400a5b7b0bb7b2aa326a95a22",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\n---\n\n\n##Assignment\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_b018a68644ffa0be738dfda155202587'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dagitty)\nlibrary(ggdag)\ndag <- dagify(\n  X ~ Z,\n  Y ~ Z,\n  Y ~ X,\n  coords = list(x = c(Y = 3, Z = 2, X = 1),\n                y = c(Y = 0, Z = 1, X = 0)),\n  labels = list(X = \"Parking spots\",\n                Y = \"Sales\",\n                Z = \"Customers\")\n)\n\n# Plot DAG\nggdag(dag) +\n  geom_dag_text(color = \"white\") +\n  geom_dag_edges(edge_color = \"black\") +\n  geom_dag_label_repel(aes(label = label))\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_a3f112b7650ae748fb14eb3edf96cb02'}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(ggplot2)\nlibrary(dagitty)\n\n# Load the data\ndata <- readRDS(\"C:\\\\Users\\\\Deniz\\\\Documents\\\\GitHub\\\\Causal_Data_Science_Data\\\\customer_sat.rds\")\n\n# Explore the data\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  follow_ups satisfaction subscription\n       <dbl>        <dbl> <chr>       \n1          8           40 Elite       \n2          7           45 Elite       \n3          8           47 Elite       \n4          9           44 Elite       \n5         10           50 Elite       \n6          6           55 Premium+    \n```\n:::\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   follow_ups      satisfaction   subscription      \n Min.   : 0.000   Min.   :40.00   Length:15         \n 1st Qu.: 2.500   1st Qu.:48.50   Class :character  \n Median : 7.000   Median :60.00   Mode  :character  \n Mean   : 5.667   Mean   :60.13                     \n 3rd Qu.: 8.000   3rd Qu.:72.00                     \n Max.   :10.000   Max.   :80.00                     \n```\n:::\n\n```{.r .cell-code}\n# Regression without accounting for subscription\nmodel1 <- lm(satisfaction ~ follow_ups, data = data)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = satisfaction ~ follow_ups, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-12.412  -5.257   1.733   4.506  12.588 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\nfollow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.923 on 13 degrees of freedom\nMultiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \nF-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n\n```{.r .cell-code}\n# Regression accounting for subscription\nmodel2 <- lm(satisfaction ~ follow_ups + subscription, data = data)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = satisfaction ~ follow_ups + subscription, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.3222 -2.1972  0.3167  2.2667  3.9944 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           26.7667     6.6804   4.007  0.00206 ** \nfollow_ups             2.1944     0.7795   2.815  0.01682 *  \nsubscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\nsubscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.958 on 11 degrees of freedom\nMultiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \nF-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\nModel 1:\n\nIntercept = 78.9\n\nFollow-up coefficient = -3.3\n\nModel 2:\n\nIntercept = 26.8\n\nFollow-up coefficient = 2.2\nSubscription Premium coefficient = 44.7\nSubscription Premium+ coefficient = 18.1\n\n\nIn the model without accounting for subscription (model1), the negative coefficient for follow-up calls suggests that more follow-up calls are associated with lower satisfaction. However, this might be confounded by the type of subscription.\n\nIn the model accounting for subscription (model2), the positive coefficient for follow-up calls suggests that, after accounting for subscription type, more follow-up calls are associated with higher satisfaction.\n\nThe positive coefficients for the \"Premium\" and \"Premium+\" subscription levels suggest that clients with these subscriptions tend to report higher satisfaction compared to the reference level.\n\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_f7b941e7d0361e29dea8c1f5bd238552'}\n\n```{.r .cell-code}\n# Plot the data\nggplot(data, aes(x = follow_ups, y = satisfaction, color = subscription)) +\n  geom_point(size = 3) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(title = \"Relationship Between Follow-up Calls and Satisfaction\",\n       x = \"Number of Follow-up Calls\",\n       y = \"Satisfaction\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}